# Site
repository: "SERDANI/serdaninicolas.github.io"
url: "https://serdani.github.io"
baseurl: "/serdaninicolas.github.io"
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Nicolas SERDANI
title: Ingénieur DevOps
email: serdaninicolas@gmail.com
email_title: Email
phone: 06 95 54 17 31
phone_title: Phone
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: nicolas-serdani

# About Section
about_title: À propos de moi
about_profile_image: images/profile.jpg
about_content: |
  Bonjour, je suis Nicolas, **Ingénieur DevOps** avec 10 ans d’expérience dans les environnements de production et l’automatisation des infrastructures.<br><br>
  Après 5 ans en tant qu’ingénieur de production et 5 ans en DevOps, j’ai acquis une expertise complète dans l’**industrialisation des environnements techniques**, l’**automatisation des processus** et la **supervision des systèmes complexes**.<br><br>
  J’ai eu l’opportunité de travailler pour des entreprises majeures telles que <mark>Orange</mark>, <mark>Euronext</mark> et actuellement <mark>Société Générale</mark>, où je contribue à la modernisation et à l’automatisation du système d’information.<br><br>
  Ce qui me motive dans ce rôle, c’est de pouvoir travailler avec des **technologies de pointe**, d’**automatiser** les processus et d’**optimiser** les environnements techniques tout en continuant à apprendre et à innover.<br><br>
  **Domaines d’expertise :**<br><br>
    - Infrastructure as Code (**Terraform**, **Ansible**)<br><br>
    - Pipelines CI/CD (**Jenkins**, **GitLab CI**, **GitHub Actions**)<br><br>
    - Orchestration de conteneurs (**Docker**, **Kubernetes**)<br><br>
    - Plateformes Cloud (**Doitnow**)<br><br>
    - Supervision et observabilité (**Grafana**, **ELK Stack**)<br><br>
    - Code (**Python**)<br><br>

content:

  - title: Expériences
    layout: list
    content:
      - layout: left
        title: Société Générale (Mission ASTRELYA)
        sub_title: Ingénieur DevOps
        caption: Février 2024 – Aujourd’hui
        link: https://www.societegenerale.com
        quote: >
          <img src="images/logo_sg.jpg" alt="Société Générale" height="30"> La Société Générale est l’un des principaux groupes bancaires européens, reconnue pour son innovation et la modernisation de son SI.
        description: |
          J’interviens sur la **modernisation des environnements techniques** et l’**automatisation des processus d’exploitation** au sein du SI de la Société Générale.

          • Mise en place et maintenance de **workflows GitHub Actions** pour la **CI/CD** des applications back-end, front-end et batchs.  
          • Automatisation complète du **déploiement** (CD) via **Helm**, **ArgoCD** et **Kubernetes**.  
          • Administration du **cloud privé DoItNow**, incluant l’intégration, la supervision et la maintenance de composants tels que **RabbitMQ**, **OpenShift (OCP)**, **PostgreSQL**, **Elasticsearch**, **Kibana**, **Vault**, **DNS** et **certificats**.  
          • **Migration des instances Grafana** vers une instance **Dataviz** pour unifier et fiabiliser le monitoring.  
          • **Migration des bases Oracle GEN1 vers GEN2** sur cloud privé (OCP), avec **automatisation du déploiement des instances via Terraform**.  
          • **Automatisation et orchestration** de tâches via **Kubernetes CronJobs** et **Python**.  
          • **Optimisation des logs** et amélioration de la **résilience des scripts Python** en production.  
          • **Documentation technique** et **partage des bonnes pratiques** au sein de l’équipe.  
          • **Support en production** et **gestion de crises**, incluant des interventions en dehors des horaires ouvrés.  
          • **Décommissionnement progressif** des environnements et services GEN1.  
          • **Veille technologique** continue sur les outils **DevOps**, **CI/CD** et **observabilité**.

      - layout: left
        title: Euronext (Mission ASTRELYA)
        sub_title: Ingénieur DevOps
        caption: Octobre 2021 – Février 2024
        link: https://www.euronext.com
        quote: >
          Euronext est la principale bourse paneuropéenne, opérant sur plusieurs marchés en Europe.
        description: |
          Intégré à l’équipe DevOps d’Euronext, j’ai travaillé sur la **centralisation des logs et métriques applicatives** afin d’offrir une meilleure observabilité et supervision.

          • Centralisation des **logs applicatifs** et **métriques systèmes** on-premises.  
          • Supervision des **métriques Kafka topics** et **MySQLd Exporter**.  
          • Modification d’une **Lambda AWS** pour collecter et centraliser les logs **CloudWatch**.  
          • **Automatisation** de l’installation et du déploiement via **Ansible** (playbooks, rôles) et **Jenkins**.  
          • Gestion du **versioning** et des **releases** via **Git**, **Jira**, **Jenkins**.  
          • Rédaction de **documentation technique** sous **Confluence**.  
          • Développement de **scripts Python** pour l’automatisation.

      - layout: left
        title: Orange (Mission UMANIS)
        sub_title: DevOps Engineer
        caption: Mai 2020 – Octobre 2021
        link: https://www.orange.com
        quote: >
          Orange est un acteur majeur des télécommunications et des services numériques en Europe.
        description: |
          Membre de l’équipe DOMA (DévelOppement-AutoMAtisation), j’ai contribué au **développement et au maintien d’automates** destinés à l’industrialisation des processus d’Orange.

          • Développement d’automates via **Ansible** et **scripts Python**.  
          • Réalisation des **phases de test** en amont du développement.  
          • Suivi de projet **agile** via **JIRA**.  
          • Hébergement et gestion du code source via **GitLab**.  
          • Création et ordonnancement de **workflows HPOO**.  
          • Mise en production et maintien en condition opérationnelle des automates.  
          • Développement d’**actions AMADEUS** pour permettre aux clients de déclencher des automates de manière autonome.  
          • **Documentation** technique et fonctionnelle.  
          • **Veille technologique** et autoformation continue.

      - layout: left
        title: BNP Paribas (Mission UMANIS)
        sub_title: Ingénieur de production informatique
        caption: Décembre 2017 – Mai 2020
        link: https://group.bnpparibas
        quote: >
          BNP Paribas est l’un des principaux groupes bancaires internationaux.
        description: |
          Administration, analyse et résolution d’incidents applicatifs impactant les environnements de production BNP Paribas.

          • Gestion et animation des **tâches problèmes** via **ITSM** et **SharePoint**.  
          • Développement et automatisation de tâches via **Shell/Bash**.  
          • Ordonnancement et supervision des chaînes de traitements via **Autosys**.  
          • Gestion et maintenance des **bases Oracle** et **MS SQL**.  
          • Administration des serveurs **WebSphere** et des comptes sécurisés (**eTac**, **Entrust**).  
          • Supervision via **Nimsoft** et gestion de l’archivage via **TSM**.  
          • Suivi et documentation via **Wiki UMANIS**.  
          • Formation et accompagnement des nouveaux arrivants.

      - layout: left
        title: BNP Paribas
        sub_title: Analyste d’exploitation (alternance)
        caption: Janvier 2015 – Décembre 2017
        link: https://group.bnpparibas
        quote: >
          Alternance au sein de l’équipe de production informatique de BNP Paribas.
        description: |
          Traitement d’incidents de production et maintien en conditions opérationnelles.

          • Administration des **bases de données** (Oracle, MS SQL).  
          • Ordonnancement automatisé via **Autosys** et **TNG**.  
          • Analyse de scripts **Shell/Bash** et gestion des **File Systems AIX/Linux**.  
          • Gestion de la **sauvegarde des données sensibles** via **TSM**.  
          • Administration **WebSphere** et supervision des transferts **CFT**.  
          • Rédaction de **documentation opérationnelle**.

      - layout: left
        title: BNP Paribas
        sub_title: Technicien de support (stage)
        caption: Avril 2014 – Juin 2014
        link: https://group.bnpparibas
        quote: >
          Stage au sein de l’équipe support IT de BNP Paribas.
        description: |
          Assistance et support technique auprès des utilisateurs, gestion du parc informatique et sécurité des données.

          • Support utilisateurs et résolution d’incidents techniques.  
          • Gestion du parc via **I-P@rk** et maintenance du matériel.  
          • Administration des utilisateurs et sécurité via **Active Directory**.

  - title: Diplômes
    layout: list
    content:
      - layout: left
        title: ETNA, école d'alternance en informatique
        sub_title: Architecte Systèmes, Réseaux et Sécurité
        caption: 2014 – 2017
        quote: >
          Formation en alternance en informatique, alliant théorie et pratique sur les systèmes, réseaux et sécurité.
        description: | 
          Obtention du master Architecte Systèmes, Réseaux et Sécurité de niveau 2.

      - layout: left
        title: Université Paris-Est Créteil (UPEC)
        sub_title: Diplôme Universitaire de Technologie en Réseaux et Télécommunications
        caption: 2012 – 2014
        quote: >
          Formation spécialisée en réseaux et télécommunications.
        description: |
          Obtention du diplôme universitaire de technologie (DUT) en Réseaux et Télécommunications.

      - layout: left
        title: Lycée Polyvalent Privé Catholique La Salle Saint-Charles (La Réunion)
        sub_title: Baccalauréat Scientifique, Sciences de la Vie et de la Terre
        caption: 2009 – 2012
        quote: >
          Formation secondaire orientée sciences.
        description: |
          Obtention du Baccalauréat Scientifique, spécialité Sciences de la Vie et de la Terre.

  - title: À propos de moi un peu plus
    layout: text
    content: |
      En dehors de mon travail en DevOps, je suis passionné par les **technologies et les jeux vidéo sur PC**, les **jeux de société** pour leur dimension stratégique, la **randonnée** et le **football**. 

      Je suis également papa et j’adore passer du temps en famille, m’amuser et partager des moments avec mon fils, ce qui me permet de développer patience, créativité et esprit d’équipe.

      Ces activités personnelles renforcent des qualités que j’applique également dans mon travail : **curiosité, persévérance, sens de l’organisation** et capacité à collaborer efficacement au sein d’équipes techniques.

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 - jekyll-remote-theme
 - jekyll-include-cache

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
  - "lib/"
  - "scripts/"
  - "docker-compose.yml"
