name: Build and Deploy Jekyll Resume

on:
  push:
    branches: ["main"]   # adapte si ton repo utilise "master"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'        # compatible avec modern-resume-theme
          bundler-cache: true         # cache les gems pour accélérer les builds

      - name: Install Nokogiri binary
        run: gem install nokogiri -v '1.10.8' -- --use-system-libraries

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Build Jekyll site
        run: bundle exec jekyll build -d ./_site
        env:
          JEKYLL_ENV: production

      - name: Configure GitHub Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Upload _site directory
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
